---
- name: Create or destroy an EC2 instance in your own VPC
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Gather facts
      setup:

  roles:
    - ansible-aws-ec2
